# Generated by Django 4.0.6 on 2022-07-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_establecimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establecimiento',
            name='id',
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='direccion',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
